# Generated by Django 5.0.3 on 2025-02-24 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileExp', '0005_folder_is_archived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='category',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
