# Generated by Django 5.0.3 on 2025-02-26 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FileExp', '0006_remove_folder_is_archived_category_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='folder',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
